[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

# autoclose 
[[plugins]]
repo = 'Townk/vim-autoclose'

# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'

# grep.vim
[[plugins]]
repo = 'vim-scripts/grep.vim'

# indent color
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# vimshell
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows() 
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_mac.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
  '''

# yank履歴を保存
[[plugins]]
repo = 'LeafCage/yankround.vim'

# lightline-vim
[[plugins]]
repo = 'itchyny/lightline.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# colorscheme
[[plugins]]
repo = 'w0ng/vim-hybrid'

# file_mru
[[plugins]]
repo = 'Shougo/neomru.vim'

# submode.vim
[[plugins]]
repo = 'kana/vim-submode'

# 補完強化
#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
#[[plugins]]
#repo = 'Shougo/neocomplete.vim'
#[[plugins]]
#repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = "thinca/vim-quickrun"
[[plugins]]
repo = "osyo-manga/shabadou.vim"
[[plugins]]
repo = "osyo-manga/vim-watchdogs"

# scala用syntax highlight
[[plugins]]
repo = 'derekwyatt/vim-scala'

# for php
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'violetyk/neocomplete-php.vim'

# syntax check
[[plugins]]
repo = 'scrooloose/syntastic'

#watchdogs
[[plugins]]
repo    = 'osyo-manga/vim-watchdogs'
depends = [
  'vim-hier',
  'quickfixstatus',
  'shabadou.vim',
  'vim-quickrun',
]
# 追記参照 2016/05/09
on_event = ['FocusLost', 'CursorHold']
hook_add = '''
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config['watchdogs_checker/_'] = {'outputter/quickfix/open_cmd': ''}
  let g:quickrun_config['watchdogs_checker/jshint'] = {'cmdopt': '--config `/.jshintrc'}
  let g:watchdogs_check_BufWritePost_enable  = 1
  let g:watchdogs_check_CursorHold_enable    = 1
'''
hook_post_source = '''
  call watchdogs#setup(g:quickrun_config)
'''
